env:
    credentials: "ENCRYPTED[4f2ed4bc06ea9b13426d3c2b0a32d822540042f7e18eab0ab30efe538432dd1b2d06b90466747f0fd2d80bdd34375f3b]"
    rcloneconfig: "ENCRYPTED[357c65638d6059f0e5cccf65c343171b4d57c4931f15a92021b76ffe272380a3d633012e0b926c2e8dc64acf681f4cbd]"
    tokentl: "ENCRYPTED[4831f48cbdfe4eb5e1638bab74422e6a4ae07d1daf9943f5e29d43687bbe9ee06751d71edb1ae64b6cd9f981181485db]"
    idtl: "ENCRYPTED[e0f6a035b67c0c702245d7f49ae3a29c7cd548c1ec498ea7e323928954e7bb7e915a1d314e7ae812005fa77718c1827d]"
    lunch: lunch rr_X00TD-user
    make: mka bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G
      greedy: true

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "texascake"
       - git config --global user.email "budalblimbing@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy queen:rr/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="🔄 Start sync RROS Source. . ."
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init -u https://github.com/strongreasons/platform_manifest -b Q
      - git clone --depth 1 https://github.com/strongreasons/local_manifest -b rr .repo/local_manifests
      - sudo apt-get update && sudo apt-get install -y git-lfs && git lfs install
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - repo forall -c 'git lfs install && git lfs pull && git lfs checkout'
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="queen"
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="🛠️ Build RROS for X00TD Started! https://cirrus-ci.com/build/$CIRRUS_BUILD_ID"
      - ./collect.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Build $(cd ~/rom/out/target/product/X00TD/ && ls RROS-*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Compress ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="📤 Uploading ccache...."
      - rclone copy ccache.tar.gz queen:rr -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Ccache Uploaded Successfully!"
